name: qt_qt
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add dependencies below as needed
  cupertino_icons: ^1.0.8
  provider: ^6.1.1 
  intl: ^0.19.0 
  shared_preferences: ^2.2.2
  mask_text_input_formatter: ^2.4.0
  flutter_svg: ^2.0.5
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for good coding practices
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  # Add assets used in the app
  assets:
    - assets/Images/QTlogo.png
